name: JIB container publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build JIB container and publish to GitHub Packages
        run: |
          mvn package com.google.cloud.tools:jib-maven-plugin:3.4.1:build \
          -Drevision=${{ github.event.release.tag_name }} \
          -Djib.to.image=docker.io/${{ github.repository }}:${{ github.event.release.tag_name }} \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.DOCKER_HUB_TOKEN }}
        shell: bash