name: publish

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
      deploy-artifacts:
        description: "True if you want to run all artifact deployments (maven & docker)"
        type: choice
        required: true
        default: 'true'
        options:
          - true
          - false
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
          fetch-tags: true
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Set projects Maven version to GitHub Action GUI set version
        run: mvn versions:set "-DnewVersion=${{ inputs.releaseversion }}"
      - name: Build artifacts and publish to Maven Central
        if: ${{ inputs.skip-deploy-artifacts == true || inputs.skip-deploy-artifacts == 'true' }}
        run: |
          mvn --batch-mode deploy -P release \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.DOCKER_HUB_TOKEN }}
        shell: bash
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.releaseversion }}',
              sha: context.sha
            })
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n#{{RELEASE_DIFF}}",
              "categories": [
                {
                  "title": "## 🚀 Enhancements",
                  "labels": ["enhancement"]
                },
                {
                  "title": "## 🐛 Fixes",
                  "labels": ["fix"]
                },
                {
                  "title": "## 🔍 Testing",
                  "labels": ["test"]
                },
                {
                  "title": "## 📘 Documentation",
                  "labels": ["documentation"]
                },
                {
                  "title": "## 🔧 Version updates",
                  "labels": ["update"]
                },
                {
                  "title": "## 📎 Others",
                  "labels": []
                }
              ]
            }
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
          fetch-tags: true
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.releaseversion }}
          release_name: ${{ inputs.releaseversion }}
          body: |
            
            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true